"""Added error to testpoint

Revision ID: c28f17b2f3d6
Revises: 2a2f874d61fe
Create Date: 2021-05-03 00:01:50.143461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28f17b2f3d6'
down_revision = '2a2f874d61fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_point', sa.Column('error', sa.Float(precision=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_point', 'error')
    # ### end Alembic commands ###
